const CARD_IMAGES: Record<number | "back", any> = {
  0: require("../../assets/images/cards/01.jpg"),
  1: require("../../assets/images/cards/02.jpg"),
  2: require("../../assets/images/cards/03.jpg"),
  3: require("../../assets/images/cards/04.jpg"),
  4: require("../../assets/images/cards/05.jpg"),
  5: require("../../assets/images/cards/06.jpg"),
  6: require("../../assets/images/cards/07.jpg"),
  7: require("../../assets/images/cards/08.jpg"),
  8: require("../../assets/images/cards/09.jpg"),
  9: require("../../assets/images/cards/10.jpg"),
  10: require("../../assets/images/cards/11.jpg"),
  11: require("../../assets/images/cards/12.jpg"),
  12: require("../../assets/images/cards/13.jpg"),
  13: require("../../assets/images/cards/14.jpg"),
  14: require("../../assets/images/cards/15.jpg"),
  15: require("../../assets/images/cards/16.jpg"),
  16: require("../../assets/images/cards/17.jpg"),
  17: require("../../assets/images/cards/18.jpg"),
  18: require("../../assets/images/cards/19.jpg"),
  19: require("../../assets/images/cards/20.jpg"),
  20: require("../../assets/images/cards/21.jpg"),
  21: require("../../assets/images/cards/22.jpg"),
  back: require("../../assets/images/cards/Rueckseite.jpg"),
};
